In [1]:
import pandas as pd
import numpy as np
from datetime import datetime
from sqlalchemy import create_engine
import pymysql
pymysql.install_as_MySQLdb()
import os
import sys, urllib, json
import time

In [2]:
class soda_data_util:
    def __init__(self, file_path, encoding='utf-8'):
        print('========================================开始读取数据========================================')
        # 读取csv表格
        self.csv_data = pd.read_csv(file_path, 
                        encoding = encoding)
        print('==================================数据读取完毕，数据的shape为:'+str(self.csv_data.shape)+"==================================")

In [5]:
host = '127.0.0.1'
port = 3306
db = 'soda_data_repo'
user = 'root'
password = '19940301'
engine = create_engine(str(r"mysql+mysqldb://%s:" + '%s' + "@%s/%s") % (user, password, host, db))
base_path = '/usr/soda_data_set/experiment_code/flow-prediction/groupByhour/'
csv_list = [base_path + 'sitedata1801_extend.csv', base_path + 'sitedata1802_extend.csv', base_path + 'sitedata1803_extend.csv']
print(len(csv_list))

3

In [8]:
for csv_path in csv_list:
    start_time = time.time()
    print(csv_path)
    df = soda_data_util(file_path= csv_path).csv_data                                
    print(df.head(10))
    df.to_sql('subway_sta_by_hour_tb', con=engine, if_exists='append', index=False)
    end_time = time.time()
    print(end_time - start_time)

/usr/soda_data_set/experiment_code/flow-prediction/groupByhour/sitedata1801_extend.csv
========================================开始读取数据========================================
==================================数据读取完毕，数据的shape为:(9703, 29)==================================
        site        data  totalrecords  totalamount  totaldiscount  time0  \
0    10号线三门路  2018-01-01          4137       9386.8           2114   12.0
1  10号线上海动物园  2018-01-01         15544      33657.9           8260   61.0
2  10号线上海图书馆  2018-01-01         10879      21075.0           5642   18.0
3    10号线五角场  2018-01-01         34443      75142.0          18627   88.0
4   10号线交通大学  2018-01-01         24281      50182.1          12931   81.0
5    10号线伊犁路  2018-01-01         10687      21573.5           5644   11.0
6   10号线南京东路  2018-01-01         63902     111797.2          29870    0.0
7   10号线同济大学  2018-01-01         20118      45785.8          11416   64.0
8   10号线四川北路  2018-01-01         14065      26910.0           7087   44.0
9    10号线国权路  2018-01-01         14297      33880.9           8007   55.0

   time1  time2  time3  time4   ...    time14  time15  time16  time17  time18  \
0    0.0    0.0    0.0    0.0   ...     259.0   287.0   300.0   360.0   284.0
1    0.0    0.0    0.0    0.0   ...    1498.0  1597.0  1801.0  1249.0   632.0
2    0.0    0.0    0.0    0.0   ...    1231.0  1527.0  1162.0   873.0   516.0
3    0.0    0.0    0.0    2.0   ...    3264.0  3326.0  3369.0  3270.0  2588.0
4    0.0    0.0    0.0    0.0   ...    2095.0  2147.0  2160.0  2146.0  1492.0
5    0.0    0.0    0.0    0.0   ...     930.0   875.0  1066.0   917.0   639.0
6    0.0    0.0    0.0    0.0   ...    6385.0  6998.0  6765.0  5857.0  5155.0
7    0.0    0.0    0.0    0.0   ...    1668.0  1663.0  1702.0  1823.0  1472.0
8    0.0    0.0    0.0    0.0   ...    1115.0  1146.0  1235.0  1236.0   932.0
9    0.0    0.0    0.0    0.0   ...    1061.0  1164.0  1148.0  1138.0   975.0

   time19  time20  time21  time22  time23
0   222.0   240.0   218.0   151.0    15.0
1   518.0   596.0   525.0   317.0    28.0
2   444.0   380.0   339.0   193.0     5.0
3  2269.0  2155.0  1754.0   925.0   171.0
4  1416.0  1483.0  1251.0   757.0    25.0
5   555.0   566.0   673.0   198.0     6.0
6  4290.0  3583.0  2868.0  1871.0   150.0
7  1347.0  1382.0  1251.0   754.0    92.0
8   763.0   760.0   657.0   445.0    26.0
9   955.0  1047.0   834.0   526.0    72.0

[10 rows x 29 columns]
0.7512919902801514
/usr/soda_data_set/experiment_code/flow-prediction/groupByhour/sitedata1802_extend.csv
========================================开始读取数据========================================
==================================数据读取完毕，数据的shape为:(8764, 29)==================================
        site        data  totalrecords  totalamount  totaldiscount  time0  \
0    10号线三门路  2018-02-01          9056      19294.1            658    0.0
1  10号线上海动物园  2018-02-01         12101      25030.1            704    0.0
2  10号线上海图书馆  2018-02-01         14620      27651.6            949    0.0
3    10号线五角场  2018-02-01         29961      63157.2           1790    0.0
4   10号线交通大学  2018-02-01         37276      73195.7           2837    0.0
5    10号线伊犁路  2018-02-01         28567      59014.8           2636    0.0
6   10号线南京东路  2018-02-01         46164      88241.0           3689    0.0
7   10号线同济大学  2018-02-01         21680      41095.5           1157    0.0
8   10号线四川北路  2018-02-01         32219      63205.6           2734    0.0
9    10号线国权路  2018-02-01         20200      39568.5           1053    0.0

   time1  time2  time3  time4   ...    time14  time15  time16  time17  time18  \
0    0.0    0.0    0.0    0.0   ...     287.0   223.0   304.0   848.0   993.0
1    0.0    0.0    0.0    0.0   ...     566.0   576.0   762.0   960.0  1128.0
2    0.0    0.0    0.0    0.0   ...     826.0   825.0  1075.0  1690.0  1175.0
3    0.0    0.0    0.0    0.0   ...    1482.0  1654.0  1715.0  2880.0  3326.0
4    0.0    0.0    0.0    0.0   ...    1502.0  1571.0  2034.0  3329.0  4058.0
5    0.0    0.0    0.0    0.0   ...    1015.0  1062.0  1354.0  3465.0  3620.0
6    0.0    0.0    0.0    0.0   ...    2481.0  2623.0  2791.0  4675.0  4291.0
7    0.0    0.0    0.0    0.0   ...     868.0   923.0  1095.0  2143.0  2245.0
8    0.0    0.0    0.0    0.0   ...    1418.0  1325.0  1455.0  3179.0  3732.0
9    0.0    0.0    0.0    0.0   ...     738.0   774.0   967.0  1742.0  2093.0

   time19  time20  time21  time22  time23
0   643.0   381.0   306.0   144.0    18.0
1   740.0   505.0   553.0   300.0    27.0
2   672.0   535.0   366.0   221.0     6.0
3  1944.0  1672.0  1613.0   813.0    65.0
4  2346.0  1570.0  1538.0   963.0    46.0
5  1254.0   907.0  1015.0   421.0     4.0
6  2514.0  2180.0  2040.0  1445.0    80.0
7  1324.0  1000.0   940.0   642.0    35.0
8  2044.0  1372.0  1053.0   521.0    20.0
9  1221.0   848.0   770.0   464.0    54.0

[10 rows x 29 columns]
0.6240522861480713
/usr/soda_data_set/experiment_code/flow-prediction/groupByhour/sitedata1803_extend.csv
========================================开始读取数据========================================
==================================数据读取完毕，数据的shape为:(9703, 29)==================================
        site        data  totalrecords  totalamount  totaldiscount  time0  \
0    10号线三门路  2018-03-01          8931      19014.0            679    0.0
1  10号线上海动物园  2018-03-01         12472      25903.6            831    0.0
2  10号线上海图书馆  2018-03-01         14227      26785.0           1010    0.0
3    10号线五角场  2018-03-01         25225      55123.6           1623    0.0
4   10号线交通大学  2018-03-01         37082      71909.8           2865    0.0
5    10号线伊犁路  2018-03-01         27412      56321.2           2543    0.0
6   10号线南京东路  2018-03-01         44512      83761.0           3860    0.0
7   10号线同济大学  2018-03-01         21001      42037.0           1195    0.0
8   10号线四川北路  2018-03-01         31126      60761.0           2795    0.0
9    10号线国权路  2018-03-01         20264      43411.0           1122    0.0

   time1  time2  time3  time4   ...    time14  time15  time16  time17  time18  \
0    0.0    0.0    0.0    0.0   ...     266.0   343.0   351.0   938.0  1019.0
1    0.0    0.0    0.0    0.0   ...     638.0   695.0   777.0  1120.0  1135.0
2    0.0    0.0    0.0    0.0   ...     716.0   950.0  1208.0  1518.0  1134.0
3    0.0    0.0    0.0    0.0   ...    1223.0  1405.0  1490.0  2591.0  2883.0
4    0.0    0.0    0.0    0.0   ...    1518.0  1694.0  2374.0  3786.0  4154.0
5    0.0    0.0    0.0    0.0   ...     957.0  1047.0  1295.0  3620.0  3627.0
6    0.0    0.0    0.0    0.0   ...    2358.0  2456.0  2710.0  4518.0  4257.0
7    0.0    0.0    0.0    0.0   ...     803.0   929.0  1131.0  2285.0  2293.0
8    0.0    0.0    0.0    0.0   ...    1314.0  1426.0  1767.0  3336.0  3795.0
9    0.0    0.0    0.0    0.0   ...     723.0   852.0  1182.0  2040.0  2300.0

   time19  time20  time21  time22  time23
0   665.0   301.0   269.0    99.0     9.0
1   686.0   450.0   421.0   209.0    16.0
2   623.0   442.0   334.0   198.0     3.0
3  1745.0  1248.0  1075.0   610.0    44.0
4  2138.0  1548.0  1231.0   671.0    25.0
5  1176.0   783.0   735.0   230.0     7.0
6  2560.0  2143.0  1623.0  1123.0    64.0
7  1219.0   967.0   801.0   434.0    39.0
8  1689.0  1016.0   753.0   392.0    16.0
9  1257.0   848.0   664.0   434.0    35.0

[10 rows x 29 columns]
0.6850452423095703